### ISSUE TITLE
Uninstall theme

### ISSUE THREAD

**Issue by aristidesfl** [Colorsublime/Colorsublime-Plugin#37]
Is there a command to uninstall themes?

**Comment by blopker** [comment]
No, there's currently no command to uninstall a theme. However, you can just remove them from the folder. 

Go to `Preferences > Browse Packages...` then open up the `Colorsublime - Themes` folder. You can remove anything you'd like in there.

Cheers!

**Comment by aristidesfl** [comment]
I could also install themes by "just" dragging them to that folder. Please re-open this issue and consider it a feature request instead of a question.

**Comment by blopker** [comment]
Yessir!

Pull requests are always welcome :)

**Comment by GianlucaGuarini** [comment]
@aristidesfl this feature does not make any sense, if you use colorsublime you will always download all its themes and the colorsublime plugin must always be in sync with [our repo](https://github.com/Colorsublime/Colorsublime-Themes) there is no way to uninstall a theme. Closing this issue as wontfix

**Comment by aristidesfl** [comment]
That doesn't describe the experience i have with colorsublime. I only have installed a few themes.

**Comment by GianlucaGuarini** [comment]
@aristidesfl here we are discussing about a feature of the colorsublime plugin that i think it doesn't make any sense. You will be still able to download and install all the themes manually if you like but the there is no need for the plugin to support themes uninstalling since they will be re downloaded on any sync event

**Comment by aristidesfl** [comment]
@GianlucaGuarini what you just said makes no sense, at least from my point of view (user). I can see the list of installed themes with [Schemr](https://packagecontrol.io/packages/Schemr). I can install themes individually by using "Colorsublime: Install Theme" action.  I should also be able to uninstall them individually with  with the equivalent opposite action "Colorsublime: Uninstall Theme".

**Comment by GianlucaGuarini** [comment]
@aristidesfl I guess `Colorsublime: Install Theme` should be renamed `Colorsublime: Show Themes` since it downloads all of them anyways. Probably having two commands like `Colorsublime: Fetch Themes` and `Colorsublime: Switch Theme` could be also a better semantic option. @blopker have you better ideas?

**Comment by aristidesfl** [comment]
@GianlucaGuarini they might be downloaded while previewing, but they don't become installed until you press enter. From the point of view of the user, the fact they are downloaded is irrelevant, since they only appear the in list of installed themes, after they have been installed.

**Comment by blopker** [comment]
I do agree using `install` here is a little non-standard since it does two things; refreshes the cache and copies files from it. Although, to the average user it's all the same I guess.

However, since there is an `install` I suppose users would expect an `uninstall` even though it's trivial to just remove the file. It's easy enough to implement anyway. I'll make a PR.
