### ISSUE TITLE
Sublime Lock up

### ISSUE THREAD

**Issue by personalnadir** [Colorsublime/Colorsublime-Plugin#42]
The plugin causes Sublime to lock up when installing a theme. Once Sublime unlocks it opens the list of themes for a frame an installs one. I have tried digging around in the code to track this one down, but can't quite figure out what is causing it. 

The lock up occurs when extracting the themes from the downloaded archive, specifically the call to the extractall function. A second lock up occurs when the plugin display_list function returns even if it is empty. 

I'm scratching my head as to what the root cause of these lock up are.

This is happening on Mac OS 10.14.1 with build 3176.

**Comment by blopker** [comment]
Unfortunately I can't reproduce. Is your hardware older or are you having other issues with your hard drive? Extracting should be pretty fast. Please let me know if you figure it out.

**Comment by personalnadir** [comment]
Thanks for getting back to me. The hardware is less than a year old, so shouldn't be an issue. I ran the plugin as a standalone application in Python 3.7 (after renaming the async decorator) and found that it completes in good time. 

I just did a clean install and it runs fine. It must be a package or a setting I have which is interfering with the plugin.

**Comment by blopker** [comment]
OK, well thanks for looking into it. Please reopen if it happens again.

**Comment by personalnadir** [comment]
It turns out that the plugin causing the issue is the [Fix Mac Path](https://github.com/int3h/SublimeFixMacPath) plugin. Unfortunately I can't get any output from the plugin to get a handle on what this is actually breaking.

**Comment by randonia** [comment]
Not sure if what I'm seeing is the same underlying root cause, but when I navigate to "Install Theme" Sublime starts pinwheeling. I don't have Fix Mac Path installed.

It's been fine until recent (~5 months?) updates to ST3. If I use the menu to change the Color Theme (`Sublime Text > Preferences > Color Scheme`) ST3 cycles through themes fine, and it even renders some of the ColorSublime themes nicely.

![2019-06-07 11 00 12](https://user-images.githubusercontent.com/483267/59124116-b1177800-8913-11e9-9a4c-63d34011b466.gif)

I even reproduced it with the `Material Theme` disabled to ensure it wasn't that. It still pinwheels 100% when opening up `Colorsublime: Install Theme` or `ColorSublime: Uninstall Theme`. Not sure how to grab additional debugging information. It freezes before the console shows anything.

FWIW, it also Pinwheels when I try to remove this theme with package manager
![image](https://user-images.githubusercontent.com/483267/59124317-33a03780-8914-11e9-97e5-217f6184e16d.png)

My stuff:
+ Sublime Text 3.2.1, Build 3207
+ MBP 15" 2014 on 10.14.1 Mojave

Hopefully this'll help other people landing here from Google.
